### ISSUE TITLE
Compile errors when using types for ReactDOMServer

### ISSUE THREAD

**Issue by sholladay** [Soremwar/deno_types#5]
To reproduce, save the following code to a file named `main.tsx`:
```tsx
import React from 'https://cdn.pika.dev/react@16.13.1';
// @deno-types="https://deno.land/x/types/react-dom/v16.13.1/server.d.ts"
import ReactDOMServer from 'https://dev.jspm.io/react-dom@16.13.1/server';

console.log(React.isValidElement(null));
console.log(ReactDOMServer.renderToStaticMarkup(<h1>Hello, World</h1>));
```

Now run:

```sh
deno run main.ts
```

### Expected output

```tsx
false
<h1>Hello, World</h1>
```

### Actual output

Tons of errors, such as...

```ts
TS2717 [ERROR]: Subsequent property declarations must have the same type.  Property 'view' must be of type 'SVGProps<SVGViewElement>', but here has type 'SVGProps<SVGViewElement>'.
      view: React.SVGProps<SVGViewElement>;
      ~~~~
    at https://deno.land/x/types/react/v16.13.1/react.d.ts:3835:7

    'view' was also declared here.
                view: React.SVGProps<SVGViewElement>;
                ~~~~
        at https://cdn.pika.dev/-/react@v16.13.1-ByypZEPVPs6cpkpGdpQK/dist=es2019,mode=types/index.d.ts:3098:13

Found 177 errors.
```

### Environment

macOS 10.14.6

```sh
❯ deno --version
deno 1.1.0
v8 8.4.300
typescript 3.9.2
```

**Comment by Soremwar** [comment]
@sholladay Just tried the following code, works perfectly on Deno v1.3.0

```javascript
import React from 'https://cdn.pika.dev/react@16.13.1';
// @deno-types="https://denopkg.com/soremwar/deno_types/react-dom/v16.13.1/react-dom.d.ts"
import ReactDOMServer from 'https://dev.jspm.io/react-dom@16.13.1/server';

console.log(React.isValidElement(null));
console.log(ReactDOMServer.renderToStaticMarkup(<h1>Hello, World</h1>));
```
